<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="prmeta" nsURI="http://avatar.de/mdp/privacyrelatedmeta/1.0.0"
    nsPrefix="prmeta">
  <eAnnotations source="Version">
    <details key="value" value="1.0.0"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="PRModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="packageURI" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="prPackage" upperBound="-1"
        eType="#//PRPackage" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PRPackage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ePackage" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EPackage"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="evaluationCriterium" eType="#//EvaluationCriteriumType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="prClassifier" upperBound="-1"
        eType="#//PRClassifier" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PRClassifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eClassifier" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EClassifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="prFeature" upperBound="-1"
        eType="#//PRFeature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relevance" upperBound="-1"
        eType="#//Relevance" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PRFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EStructuralFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relevance" upperBound="-1"
        eType="#//Relevance" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relevance">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="#//RelevanceLevelType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EvaluationCriteriumType">
    <eLiterals name="NONE"/>
    <eLiterals name="GDPR" value="1"/>
    <eLiterals name="OPEN_DATA" value="2"/>
    <eLiterals name="OTHER" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RelevanceLevelType">
    <eLiterals name="NOT_RELEVANT"/>
    <eLiterals name="POTENTIALLY_RELEVANT" value="1"/>
    <eLiterals name="RELEVANT" value="2"/>
  </eClassifiers>
</ecore:EPackage>
